#!/usr/bin/env tsx
import * as fs from "fs/promises";
import { watch } from "fs";
import * as path from "path";
import { iconLibraries, type IconLibraryName } from "shadcn-svelte/icons";

const SEARCH_BASE = "src/";
const REGISTRY_BASE = "src/lib/registry";

type IconUsage = Record<IconLibraryName, Set<string>>;

async function findSvelteFiles(dir: string) {
	const files: string[] = [];
	const entries = await fs.readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await findSvelteFiles(fullPath)));
		} else if (entry.isFile() && entry.name.endsWith(".svelte")) {
			files.push(fullPath);
		}
	}

	return files;
}

async function scanIconUsage() {
	const iconUsage = Object.fromEntries(
		Object.keys(iconLibraries).map((key) => [key, new Set<string>()])
	) as IconUsage;

	const searchBasesDir = path.join(process.cwd(), SEARCH_BASE);
	const files = await findSvelteFiles(searchBasesDir);

	for (const file of files) {
		const content = await fs.readFile(file, "utf-8");

		for (const [libraryName, config] of Object.entries(iconLibraries)) {
			const regex = new RegExp(`${config.name}=["']([^"']+)["']`, "g");
			let match;
			while ((match = regex.exec(content)) !== null) {
				iconUsage[libraryName as IconLibraryName].add(match[1]);
			}
		}
	}

	return iconUsage;
}

async function isPackageInstalled(packageName: string): Promise<boolean> {
	try {
		// Use existsSync on the node_modules dir to support ESM-only packages
		// that lack a "main" field and break require.resolve().
		const { existsSync } = await import("fs");
		const pkgDir = path.join(process.cwd(), "node_modules", packageName);
		return existsSync(pkgDir);
	} catch {
		return false;
	}
}

async function generateIconFiles(iconUsage: IconUsage) {
	const outputDir = path.join(process.cwd(), REGISTRY_BASE, "icons");

	const completedLibraries: { name: IconLibraryName; icons: string[] }[] = [];

	for (const [lib, config] of Object.entries(iconLibraries)) {
		const libraryName = lib as IconLibraryName;
		const icons = Array.from(iconUsage[libraryName]).sort();

		if (icons.length === 0) {
			continue;
		}

		// Check if the library's package is installed before generating files.
		const sampleExport = iconLibraries[libraryName].export({ name: icons[0] });
		const packageMatch = sampleExport.match(/from ['"]([^'"]+)['"]/);
		if (packageMatch) {
			const rawImport = packageMatch[1];
			// Extract top-level package name (handles scoped packages like @lucide/svelte)
			const packageName = rawImport.startsWith("@")
				? rawImport.split("/").slice(0, 2).join("/")
				: rawImport.split("/")[0];
			const installed = await isPackageInstalled(packageName);
			if (!installed) {
				console.log(`  ⚠ Skipping ${libraryName}: package "${packageName}" not installed`);
				// Remove previously generated dir if it exists.
				const staleDir = path.join(outputDir, `__${libraryName}__`);
				await fs.rm(staleDir, { recursive: true, force: true });
				continue;
			}
		}

		const typeName = `${config.title.replace(/\s/g, "")}IconName`;
		const typeUnion = icons.map((icon) => `"${icon}"`).join(" | ");

		const indexFileContent = `// Auto-generated by scripts/build-icons.ts
export type ${typeName} = ${typeUnion};
`;

		const dirname = `__${libraryName}__`;
		const iconDir = path.join(outputDir, dirname);
		const iconOutputDir = path.join(outputDir, dirname);

		const iconFiles = icons.map((icon) => {
			const iconExport = iconLibraries[libraryName].export({ name: icon });
			const fileName = `${icon}.ts`;

			return {
				name: icon,
				fileName,
				path: path.join(iconOutputDir, fileName),
				content: `// Auto-generated by scripts/build-icons.ts\n${iconExport}\n`,
			};
		});

		await fs.mkdir(iconDir, { recursive: true });
		await fs.mkdir(outputDir, { recursive: true });
		await fs.writeFile(path.join(iconOutputDir, "index.ts"), indexFileContent);
		for (const iconFile of iconFiles) {
			await fs.writeFile(iconFile.path, iconFile.content);
		}

		// clean unused icon files
		const iconFileSet = new Set([
			"index.ts",
			...iconFiles.map((iconFile) => iconFile.fileName),
		]);
		for (const existingIconFile of await fs.readdir(iconOutputDir)) {
			if (!iconFileSet.has(existingIconFile)) {
				await fs.rm(path.join(iconOutputDir, existingIconFile));
			}
		}

		completedLibraries.push({ name: libraryName, icons });
	}

	console.log("✓ Generated icon files:");

	for (const library of completedLibraries) {
		console.log(`  - ${library.name}: ${library.icons.length} icons`);
	}
}

async function main() {
	const iconUsage = await scanIconUsage();
	await generateIconFiles(iconUsage);
}

const isWatchMode = process.argv.includes("--watch");

if (isWatchMode) {
	const SEARCH_DIR = path.join(process.cwd(), SEARCH_BASE);

	await main();

	watch(SEARCH_DIR, { recursive: true }, (_, filename) => {
		if (!filename?.endsWith(".svelte")) return;
		if (filename.includes("registry/icons/__")) return;
		if (filename.includes("components/icon-placeholder")) return;
		main().catch((error) => {
			console.error("❌ Icons build failed:", error);
		});
	});
} else {
	await main();
}
